export { BackgroundSessionManager, bgSessionManager } from './manager'
export { needsResultGuard, RESULT_GUARD_PROMPT, extractFallbackResult } from './resultGuard'
export { observerRegistry } from './observerRegistry'
export { buildBgSystemPreamble } from './preambleBuilder'
export { validateJsonSchema } from './schemaValidation'
export type { ObserverCallbacks } from './observerRegistry'
export type { BgTriggerPayload, BgRunResult, ActiveRunEntry, BgConcurrencyLimits } from './types'
